#!/bin/bash

if [[ ! -z "${NO_LINT}" ]] ; then
  exit
fi

if ! type rubocop-git >/dev/null 2>&1 ; then
  echo "😢  Please run: gem install rubocop-git"
  exit 125
fi

if [[ $(git diff --name-only --cached) ]]; then
  rubocop-git --staged
else
  rubocop-git
fi
